40-delits-a-la-police-des-etrangers-evolution-de-l-action-des-services-index-69-30379700
accompagnement-des-conjoints-du-personnels-de-la-defense-et-de-la-gendarmerie-572871
carte-des-points-d-accueil-police-a-paris-idf
cartographie-des-emplacements-des-commissariats-a-paris-et-petite-couronne-idf
classes-defense-et-securite-globales-571315
coherence-et-efficacite-des-politiques-cas-d-infractions-nouveaux-de-1997-a-2009-dp
crimes-et-delits-constates-en-2013-par-les-services-de-la-police-nationale
crimes-et-delits-constates-par-la-police-nationale-en-2013
crimes-et-delits-enregistres-par-la-police-nationale-en-2013
crimes-et-delits-enregistres-par-les-services-de-police-et-les-unites-de-gendarmerie-571598
delinquance-violence-ou-vandalisme-aux-alentours-source-silc-dp
evolution-des-effectifs-totaux-de-la-defense-hors-gendarmerie-564789
faits-constates-mensuels-par-departements
faits-constates-par-departement-par-index-et-par-mois
faits-constates-par-index-par-departement-et-par-annee
faits-constates-zone-gendarmerie-00000000
faits-constates-zone-police-00000000
homicides-intentionnels-pour-100-000-personnes-de-1995-a-2010-dp
incidents-tic-lies-a-la-securite-et-consequences-dp
infractions-enregistrees-par-la-police-donnees-historiques-crime-total-1950-2000-dp
infractions-enregistrees-par-la-police-dp
infractions-enregistrees-par-la-police-homicides-dans-les-villes-principales-dp
infractions-enregistrees-par-la-police-regions-nuts-3-dp
jeunes-et-justice-1945-2005-collection-politiques-publiques
la-politique-de-defense-1945-2014-collection-politiques-publiques
la-politique-de-la-route-et-de-securite-routiere-jusqu-en-2005-collection-politiques-publiques
la-politique-de-securite-risques-abordes-et-sensibilisation-du-personnel-dp
la-securite-interieure-1995-2005-collection-politiques-publiques
la-securite-routiere-en-france-bilan-annuel-30379646
les-crimes-et-delits-enregistres-par-la-gendarmerie-nationa-0
les-crimes-et-delits-enregistres-par-la-gendarmerie-nationale
les-crimes-et-delits-enregistres-par-la-police-nationa-0
les-crimes-et-delits-enregistres-par-la-police-nationa-1
les-crimes-et-delits-enregistres-par-la-police-nationale
les-polices-municipales-par-commune
liste-des-points-d-accueil-de-la-gendarmerie-nationale
officiers-de-police-dp
personnes-detenues-donnees-historiques-1987-2000-dp
personnes-detenues-dp
personnes-tuees-dans-les-accidents-de-la-route-dp
pertes-attribuables-a-des-vols-des-vols-qualifies-du-vandalisme-et-des-incendies-criminels-des-ve-dp
points-d-accueil-police-coordonnees-paris-30379560
points-d-accueil-police-coordonnees-petite-couronne-30379776
points-d-accueil-police-coordonnees-province-30379510
police-municipale
polices-municipales-de-france-2012
presence-des-forces-de-securite-effectif-des-troupes-des-forces-de-police-et-des-observateurs-mil-dp
securite-routiere-et-accidentologie-a-paris-bilan-2007-551646
tranquillite-securite-et-gestion-des-quartiers-30383110
unites-de-gendarmerie-accueillant-du-public-en-idf-idf
videoprotection-implantation-des-cameras-551635
